# See: https://dart.dev/tools/pub/pubspec
name: openxr
version: 0.0.1
description: >-
  OpenXR.dart implements Dart bindings for OpenXR 1.0, the open standard and
  cross-platform API for virtual reality (VR) and augmented reality (AR)
  hardware.
homepage: https://github.com/drydart/openxr.dart
repository: https://github.com/drydart/openxr.dart
issue_tracker: https://github.com/drydart/openxr.dart/issues
documentation:
dependencies:
  meta: ^1.1.8
dev_dependencies:
  test: any
dependency_overrides:
environment:
  sdk: '>=2.8.1 <3.0.0'
executables:
